import type { Property } from "./data";

const agents = [
  { name: "Chidi Okafor", phone: "+234 801 234 5678", image: "" },
  { name: "Amina Bello", phone: "+234 802 345 6789", image: "" },
  { name: "Osaze Omoruyi", phone: "+234 803 456 7890", image: "" },
  { name: "Efe Okoro", phone: "+234 804 567 8901", image: "" },
  { name: "Tunde Adeyemi", phone: "+234 805 678 9012", image: "" },
  { name: "Ngozi Ibe", phone: "+234 806 789 0123", image: "" },
  { name: "Emeka Nwosu", phone: "+234 807 890 1234", image: "" },
  { name: "Chioma Eze", phone: "+234 808 901 2345", image: "" },
  { name: "Folake Adebayo", phone: "+234 809 012 3456", image: "" },
  { name: "Uche Obi", phone: "+234 810 123 4567", image: "" },
  { name: "Halima Yusuf", phone: "+234 811 234 5678", image: "" },
  { name: "Blessing Okoh", phone: "+234 812 345 6789", image: "" },
  { name: "Kola Bankole", phone: "+234 813 456 7890", image: "" },
  { name: "Ifeoma Nwachukwu", phone: "+234 814 567 8901", image: "" },
  { name: "Yemi Alade", phone: "+234 815 678 9012", image: "" },
];

function agent(i: number) { return agents[i % agents.length]; }
function img(i: number) { return `property-${((i - 1) % 6) + 1}`; }

export const allProperties: Property[] = [
  // Lagos
  { id: "1", title: "Luxury 3-Bedroom Apartment", location: "Lekki Phase 1, Lagos", city: "Lagos", state: "Lagos", lga: "Eti-Osa", price: 4500000, priceLabel: "₦4,500,000/yr", beds: 3, baths: 3, type: "Apartment", image: img(1), verified: true, featured: true, furnished: false, sqm: 150, parking: 2, amenities: ["Borehole", "24/7 Security", "Parking", "Generator Backup", "Prepaid Meter", "Swimming Pool"], description: "Exquisite 3-bedroom apartment in the heart of Lekki Phase 1. Features modern finishes, spacious living areas, and stunning city views. Fully serviced estate with 24/7 security, swimming pool, and gym access.", agent: agent(0) },
  { id: "2", title: "Modern Mini Flat in Yaba", location: "Yaba, Lagos", city: "Lagos", state: "Lagos", lga: "Lagos Mainland", price: 1200000, priceLabel: "₦1,200,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: true, featured: false, furnished: false, sqm: 45, parking: 0, amenities: ["Prepaid Meter", "Security", "POP Ceiling"], description: "Contemporary mini flat in the heart of Yaba. Perfect for young professionals. Close to tech hubs, restaurants, and public transport.", agent: agent(4) },
  { id: "3", title: "2-Bedroom Flat in Ikeja GRA", location: "Ikeja GRA, Lagos", city: "Lagos", state: "Lagos", lga: "Ikeja", price: 3500000, priceLabel: "₦3,500,000/yr", beds: 2, baths: 2, type: "Apartment", image: img(3), verified: true, featured: true, furnished: false, sqm: 110, parking: 1, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Prepaid Meter"], description: "Well-maintained 2-bedroom flat in the prestigious Ikeja GRA. Quiet neighborhood with good road access and proximity to the airport.", agent: agent(8) },
  { id: "4", title: "4-Bedroom Duplex in Ajah", location: "Ajah, Lagos", city: "Lagos", state: "Lagos", lga: "Eti-Osa", price: 55000000, priceLabel: "₦55,000,000", beds: 4, baths: 4, type: "Duplex", image: img(2), verified: true, featured: true, furnished: false, sqm: 250, parking: 3, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound", "Boys Quarter"], description: "Magnificent 4-bedroom duplex in Ajah. Newly built with premium finishes, spacious compound, and modern amenities. Ideal for families.", agent: agent(0) },
  { id: "5", title: "Furnished Shortlet in Victoria Island", location: "Victoria Island, Lagos", city: "Lagos", state: "Lagos", lga: "Eti-Osa", price: 85000, priceLabel: "₦85,000/night", beds: 2, baths: 2, type: "Shortlet", image: img(4), verified: true, featured: true, furnished: true, sqm: 100, parking: 1, amenities: ["AC", "WiFi", "Generator Backup", "Parking", "Smart TV", "Swimming Pool"], description: "Premium furnished shortlet on Victoria Island. Ocean views, fully air-conditioned, high-speed WiFi, and concierge service. Perfect for business travelers and tourists.", agent: agent(3) },
  { id: "6", title: "Self Contain in Surulere", location: "Surulere, Lagos", city: "Lagos", state: "Lagos", lga: "Surulere", price: 600000, priceLabel: "₦600,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: true, featured: false, furnished: false, sqm: 30, parking: 0, amenities: ["Prepaid Meter", "Security", "POP Ceiling"], description: "Affordable self-contained apartment in Surulere. Close to the stadium, shopping malls, and public transport. Ideal for singles.", agent: agent(12) },
  { id: "7", title: "Luxury Penthouse in Ikoyi", location: "Ikoyi, Lagos", city: "Lagos", state: "Lagos", lga: "Eti-Osa", price: 15000000, priceLabel: "₦15,000,000/yr", beds: 4, baths: 4, type: "Apartment", image: img(1), verified: true, featured: true, furnished: true, sqm: 300, parking: 3, amenities: ["Swimming Pool", "Gym", "24/7 Security", "Generator Backup", "AC", "Smart Home", "Elevator"], description: "Breathtaking penthouse apartment in Ikoyi with panoramic Lagos lagoon views. Smart home features, infinity pool, and private elevator access.", agent: agent(0) },
  { id: "8", title: "3-Bedroom Flat in Lekki Phase 2", location: "Lekki Phase 2, Lagos", city: "Lagos", state: "Lagos", lga: "Eti-Osa", price: 3000000, priceLabel: "₦3,000,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 120, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter", "POP Ceiling"], description: "Spacious 3-bedroom flat in a secure estate in Lekki Phase 2. Well-ventilated rooms, modern kitchen, and ample parking space.", agent: agent(4) },
  { id: "9", title: "Studio Apartment in Yaba", location: "Yaba, Lagos", city: "Lagos", state: "Lagos", lga: "Lagos Mainland", price: 900000, priceLabel: "₦900,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: false, featured: false, furnished: false, sqm: 25, parking: 0, amenities: ["Prepaid Meter", "Security"], description: "Compact studio apartment in Yaba, perfect for students and young professionals working in the tech corridor.", agent: agent(4) },
  // Abuja
  { id: "10", title: "5-Bedroom Detached Duplex", location: "Gwarinpa, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 85000000, priceLabel: "₦85,000,000", beds: 5, baths: 5, type: "Duplex", image: img(2), verified: true, featured: true, furnished: false, sqm: 350, parking: 4, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Boys Quarter", "Garden"], description: "Massive 5-bedroom fully detached duplex in Gwarinpa estate. Well-maintained compound with beautiful garden, security fence, and spacious rooms.", agent: agent(1) },
  { id: "11", title: "3-Bedroom Apartment in Maitama", location: "Maitama, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 6000000, priceLabel: "₦6,000,000/yr", beds: 3, baths: 3, type: "Apartment", image: img(1), verified: true, featured: true, furnished: false, sqm: 160, parking: 2, amenities: ["Borehole", "24/7 Security", "Parking", "Generator Backup", "Swimming Pool", "Gym"], description: "Premium 3-bedroom apartment in the exclusive Maitama district. Close to embassies, international schools, and fine dining.", agent: agent(1) },
  { id: "12", title: "Luxury Shortlet in Wuse 2", location: "Wuse 2, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 60000, priceLabel: "₦60,000/night", beds: 2, baths: 2, type: "Shortlet", image: img(4), verified: true, featured: false, furnished: true, sqm: 90, parking: 1, amenities: ["AC", "WiFi", "Smart TV", "Generator Backup", "Parking", "Kitchen"], description: "Stylish furnished shortlet in the heart of Wuse 2. Walking distance to restaurants, shopping malls, and nightlife.", agent: agent(10) },
  { id: "13", title: "4-Bedroom Semi-Detached in Jabi", location: "Jabi, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 45000000, priceLabel: "₦45,000,000", beds: 4, baths: 4, type: "Duplex", image: img(6), verified: true, featured: false, furnished: false, sqm: 280, parking: 3, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound"], description: "Beautiful semi-detached duplex in Jabi. Close to Jabi Lake Mall, with modern finishes and a well-maintained estate.", agent: agent(1) },
  { id: "14", title: "2-Bedroom Flat in Lugbe", location: "Lugbe, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 1800000, priceLabel: "₦1,800,000/yr", beds: 2, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 85, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Affordable 2-bedroom flat in Lugbe. Good road network and proximity to the airport. Great for young families.", agent: agent(10) },
  { id: "15", title: "Executive 3-Bed in Asokoro", location: "Asokoro, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 8000000, priceLabel: "₦8,000,000/yr", beds: 3, baths: 3, type: "Apartment", image: img(1), verified: true, featured: true, furnished: false, sqm: 200, parking: 2, amenities: ["Borehole", "24/7 Security", "Parking", "Generator Backup", "Swimming Pool", "Gym", "Elevator"], description: "Ultra-premium apartment in the diplomatic zone of Asokoro. World-class amenities, concierge service, and serene environment.", agent: agent(1) },
  // Rivers / Port Harcourt
  { id: "16", title: "4-Bedroom Detached House", location: "GRA, Port Harcourt", city: "Port Harcourt", state: "Rivers", lga: "Port Harcourt", price: 65000000, priceLabel: "₦65,000,000", beds: 4, baths: 4, type: "Duplex", image: img(6), verified: true, featured: true, furnished: false, sqm: 300, parking: 3, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Garden", "Boys Quarter"], description: "Premium 4-bedroom detached house in the exclusive GRA area. Large compound, beautiful garden, and top-notch security.", agent: agent(5) },
  { id: "17", title: "3-Bedroom Flat in Rumuola", location: "Rumuola, Port Harcourt", city: "Port Harcourt", state: "Rivers", lga: "Obio-Akpor", price: 2500000, priceLabel: "₦2,500,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 120, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter", "POP Ceiling"], description: "Spacious 3-bedroom flat in Rumuola. Close to major roads, shopping centers, and commercial areas.", agent: agent(5) },
  { id: "18", title: "2-Bedroom Shortlet in Trans Amadi", location: "Trans Amadi, Port Harcourt", city: "Port Harcourt", state: "Rivers", lga: "Obio-Akpor", price: 45000, priceLabel: "₦45,000/night", beds: 2, baths: 2, type: "Shortlet", image: img(4), verified: true, featured: false, furnished: true, sqm: 80, parking: 1, amenities: ["AC", "WiFi", "Smart TV", "Generator Backup", "Parking"], description: "Comfortable furnished shortlet in the Trans Amadi industrial area. Ideal for business travelers and oil industry professionals.", agent: agent(5) },
  // Edo / Benin City
  { id: "19", title: "Student Hostel near UNIBEN", location: "Ugbowo, Benin City", city: "Benin City", state: "Edo", lga: "Oredo", price: 250000, priceLabel: "₦250,000/yr", beds: 1, baths: 1, type: "Student Lodge", image: img(3), verified: true, featured: false, furnished: false, sqm: 20, parking: 0, amenities: ["Borehole", "Security", "Prepaid Meter"], description: "Clean and affordable student accommodation near the University of Benin. Ugbowo axis with easy access to campus.", agent: agent(2) },
  { id: "20", title: "3-Bedroom Flat in GRA Benin", location: "GRA, Benin City", city: "Benin City", state: "Edo", lga: "Oredo", price: 1500000, priceLabel: "₦1,500,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 110, parking: 1, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Prepaid Meter"], description: "Lovely 3-bedroom flat in the quiet GRA area of Benin City. Well-finished with modern amenities.", agent: agent(2) },
  { id: "21", title: "Self Contain near UBTH", location: "Uselu, Benin City", city: "Benin City", state: "Edo", lga: "Egor", price: 300000, priceLabel: "₦300,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: true, featured: false, furnished: false, sqm: 25, parking: 0, amenities: ["Prepaid Meter", "Security"], description: "Affordable self-contained near UBTH and UNIBEN. Perfect for students and medical interns.", agent: agent(2) },
  { id: "22", title: "4-Bedroom Duplex in Benin", location: "Sapele Road, Benin City", city: "Benin City", state: "Edo", lga: "Ikpoba-Okha", price: 35000000, priceLabel: "₦35,000,000", beds: 4, baths: 3, type: "Duplex", image: img(2), verified: true, featured: true, furnished: false, sqm: 220, parking: 2, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound", "Garden"], description: "Exquisite 4-bedroom duplex along Sapele Road. Newly built with premium finishes and large compound.", agent: agent(2) },
  // Delta
  { id: "23", title: "Furnished Shortlet in Asaba", location: "Asaba, Delta", city: "Asaba", state: "Delta", lga: "Oshimili South", price: 35000, priceLabel: "₦35,000/night", beds: 2, baths: 2, type: "Shortlet", image: img(4), verified: true, featured: true, furnished: true, sqm: 80, parking: 1, amenities: ["AC", "WiFi", "Generator Backup", "Parking", "Smart TV"], description: "Beautifully furnished shortlet apartment in Asaba. Fully air-conditioned with reliable WiFi and backup generator.", agent: agent(3) },
  { id: "24", title: "3-Bedroom Flat in Warri", location: "Effurun, Warri", city: "Warri", state: "Delta", lga: "Uvwie", price: 1200000, priceLabel: "₦1,200,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 100, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Spacious 3-bedroom flat in Effurun. Close to major markets, schools, and the refinery.", agent: agent(3) },
  { id: "25", title: "2-Bedroom Flat in Asaba", location: "Cable Point, Asaba", city: "Asaba", state: "Delta", lga: "Oshimili South", price: 900000, priceLabel: "₦900,000/yr", beds: 2, baths: 1, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 70, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Neat 2-bedroom flat in the Cable Point area of Asaba. Quiet and secure neighborhood.", agent: agent(3) },
  // Enugu
  { id: "26", title: "2-Bedroom Flat in Enugu", location: "Independence Layout, Enugu", city: "Enugu", state: "Enugu", lga: "Enugu North", price: 800000, priceLabel: "₦800,000/yr", beds: 2, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 85, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Spacious 2-bedroom flat in the serene Independence Layout. Close to major amenities, schools, and markets.", agent: agent(6) },
  { id: "27", title: "3-Bedroom Duplex in New Haven", location: "New Haven, Enugu", city: "Enugu", state: "Enugu", lga: "Enugu North", price: 25000000, priceLabel: "₦25,000,000", beds: 3, baths: 3, type: "Duplex", image: img(2), verified: true, featured: false, furnished: false, sqm: 180, parking: 2, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound"], description: "Modern 3-bedroom duplex in New Haven. Premium finishes with a large compound and excellent security.", agent: agent(6) },
  { id: "28", title: "Student Lodge near ESUT", location: "Agbani, Enugu", city: "Enugu", state: "Enugu", lga: "Nkanu West", price: 200000, priceLabel: "₦200,000/yr", beds: 1, baths: 1, type: "Student Lodge", image: img(3), verified: true, featured: false, furnished: false, sqm: 18, parking: 0, amenities: ["Borehole", "Security"], description: "Clean student lodge near ESUT campus. Affordable and secure with water supply.", agent: agent(6) },
  // Anambra
  { id: "29", title: "Executive 3-Bed Apartment in Awka", location: "Awka, Anambra", city: "Awka", state: "Anambra", lga: "Awka South", price: 1500000, priceLabel: "₦1,500,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 120, parking: 1, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "POP Ceiling"], description: "Executive 3-bedroom apartment in Awka with modern finishing. Quiet neighborhood ideal for families.", agent: agent(7) },
  { id: "30", title: "5-Bedroom Duplex in Onitsha", location: "GRA, Onitsha", city: "Onitsha", state: "Anambra", lga: "Onitsha South", price: 60000000, priceLabel: "₦60,000,000", beds: 5, baths: 5, type: "Duplex", image: img(6), verified: true, featured: true, furnished: false, sqm: 400, parking: 4, amenities: ["Borehole", "24/7 Security", "Parking", "Generator Backup", "Swimming Pool", "Boys Quarter", "Garden"], description: "Magnificent 5-bedroom duplex in Onitsha GRA. Massive compound with swimming pool and manicured gardens.", agent: agent(7) },
  // Oyo / Ibadan
  { id: "31", title: "3-Bedroom Flat in Bodija", location: "Bodija, Ibadan", city: "Ibadan", state: "Oyo", lga: "Ibadan North", price: 1000000, priceLabel: "₦1,000,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 100, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Comfortable 3-bedroom flat in the serene Bodija area of Ibadan. Close to UCH and University of Ibadan.", agent: agent(12) },
  { id: "32", title: "4-Bedroom Duplex in Oluyole", location: "Oluyole Estate, Ibadan", city: "Ibadan", state: "Oyo", lga: "Ibadan South-West", price: 30000000, priceLabel: "₦30,000,000", beds: 4, baths: 3, type: "Duplex", image: img(2), verified: true, featured: false, furnished: false, sqm: 250, parking: 2, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound"], description: "Well-built duplex in Oluyole Estate. Gated community with good infrastructure.", agent: agent(12) },
  { id: "33", title: "Mini Flat near UI", location: "Agbowo, Ibadan", city: "Ibadan", state: "Oyo", lga: "Ibadan North", price: 250000, priceLabel: "₦250,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: true, featured: false, furnished: false, sqm: 22, parking: 0, amenities: ["Prepaid Meter", "Security"], description: "Affordable mini flat near the University of Ibadan. Perfect for students.", agent: agent(12) },
  // Ogun
  { id: "34", title: "3-Bedroom Flat in Abeokuta", location: "Oke-Ilewo, Abeokuta", city: "Abeokuta", state: "Ogun", lga: "Abeokuta South", price: 800000, priceLabel: "₦800,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 95, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Neat 3-bedroom flat in the heart of Abeokuta. Close to Olumo Rock and major markets.", agent: agent(12) },
  { id: "35", title: "4-Bedroom Duplex in Ota", location: "Ota, Ogun", city: "Ota", state: "Ogun", lga: "Ado-Odo/Ota", price: 28000000, priceLabel: "₦28,000,000", beds: 4, baths: 3, type: "Duplex", image: img(6), verified: true, featured: false, furnished: false, sqm: 220, parking: 2, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound"], description: "Spacious duplex in Ota. Strategic location close to Lagos border and industrial areas.", agent: agent(8) },
  // Kaduna
  { id: "36", title: "3-Bedroom Flat in Kaduna", location: "Barnawa, Kaduna", city: "Kaduna", state: "Kaduna", lga: "Kaduna South", price: 900000, priceLabel: "₦900,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 100, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Well-maintained 3-bedroom flat in Barnawa, Kaduna. Quiet residential area with good schools nearby.", agent: agent(10) },
  { id: "37", title: "5-Bedroom Mansion in Kaduna GRA", location: "GRA, Kaduna", city: "Kaduna", state: "Kaduna", lga: "Kaduna North", price: 70000000, priceLabel: "₦70,000,000", beds: 5, baths: 5, type: "Duplex", image: img(2), verified: true, featured: true, furnished: false, sqm: 450, parking: 5, amenities: ["Borehole", "24/7 Security", "Parking", "Generator Backup", "Swimming Pool", "Boys Quarter", "Garden", "CCTV"], description: "Opulent 5-bedroom mansion in Kaduna GRA with swimming pool, home cinema, and manicured gardens.", agent: agent(10) },
  // Kano
  { id: "38", title: "3-Bedroom Flat in Kano", location: "Nassarawa, Kano", city: "Kano", state: "Kano", lga: "Nassarawa", price: 700000, priceLabel: "₦700,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 90, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Comfortable 3-bedroom flat in Nassarawa, Kano. Close to major markets and commercial areas.", agent: agent(10) },
  { id: "39", title: "4-Bedroom Duplex in Kano GRA", location: "GRA, Kano", city: "Kano", state: "Kano", lga: "Kano Municipal", price: 40000000, priceLabel: "₦40,000,000", beds: 4, baths: 4, type: "Duplex", image: img(6), verified: true, featured: false, furnished: false, sqm: 280, parking: 3, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound", "Garden"], description: "Elegant duplex in the heart of Kano GRA. Well-built with quality finishes and a large compound.", agent: agent(10) },
  // Imo / Owerri
  { id: "40", title: "2-Bedroom Flat in Owerri", location: "New Owerri, Imo", city: "Owerri", state: "Imo", lga: "Owerri Municipal", price: 700000, priceLabel: "₦700,000/yr", beds: 2, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 75, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Modern 2-bedroom flat in New Owerri. Close to entertainment spots and commercial centers.", agent: agent(13) },
  { id: "41", title: "3-Bedroom Duplex in Owerri", location: "World Bank, Owerri", city: "Owerri", state: "Imo", lga: "Owerri Municipal", price: 20000000, priceLabel: "₦20,000,000", beds: 3, baths: 3, type: "Duplex", image: img(2), verified: true, featured: false, furnished: false, sqm: 180, parking: 2, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound"], description: "Lovely duplex in the World Bank Housing Estate area. Well-maintained with modern finishes.", agent: agent(13) },
  // Akwa Ibom / Uyo
  { id: "42", title: "3-Bedroom Flat in Uyo", location: "Ewet Housing, Uyo", city: "Uyo", state: "Akwa Ibom", lga: "Uyo", price: 1000000, priceLabel: "₦1,000,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 100, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter", "POP Ceiling"], description: "Spacious 3-bedroom flat in Ewet Housing Estate. Clean environment with reliable water supply.", agent: agent(11) },
  { id: "43", title: "4-Bedroom Duplex in Uyo", location: "Shelter Afrique, Uyo", city: "Uyo", state: "Akwa Ibom", lga: "Uyo", price: 35000000, priceLabel: "₦35,000,000", beds: 4, baths: 4, type: "Duplex", image: img(6), verified: true, featured: false, furnished: false, sqm: 250, parking: 3, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Fenced Compound", "Garden"], description: "Premium duplex in the prestigious Shelter Afrique estate. Excellent security and well-paved roads.", agent: agent(11) },
  // Abia
  { id: "44", title: "2-Bedroom Flat in Aba", location: "Aba, Abia", city: "Aba", state: "Abia", lga: "Aba South", price: 500000, priceLabel: "₦500,000/yr", beds: 2, baths: 1, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 65, parking: 0, amenities: ["Borehole", "Security", "Prepaid Meter"], description: "Affordable 2-bedroom flat in Aba. Close to Ariaria Market and major commercial centers.", agent: agent(13) },
  { id: "45", title: "3-Bedroom Flat in Umuahia", location: "World Bank, Umuahia", city: "Umuahia", state: "Abia", lga: "Umuahia North", price: 600000, priceLabel: "₦600,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 90, parking: 1, amenities: ["Borehole", "Security", "Parking"], description: "Comfortable 3-bedroom flat in the state capital. Quiet environment near government offices.", agent: agent(13) },
  // Cross River / Calabar
  { id: "46", title: "3-Bedroom Flat in Calabar", location: "State Housing, Calabar", city: "Calabar", state: "Cross River", lga: "Calabar Municipal", price: 900000, priceLabel: "₦900,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 95, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Lovely 3-bedroom flat in the serene State Housing Estate. Great views and peaceful atmosphere.", agent: agent(14) },
  { id: "47", title: "Furnished Shortlet in Calabar", location: "Marian, Calabar", city: "Calabar", state: "Cross River", lga: "Calabar South", price: 30000, priceLabel: "₦30,000/night", beds: 2, baths: 2, type: "Shortlet", image: img(4), verified: true, featured: false, furnished: true, sqm: 70, parking: 1, amenities: ["AC", "WiFi", "Smart TV", "Generator Backup", "Parking"], description: "Cozy furnished shortlet in Calabar. Close to the waterfront and tourist attractions.", agent: agent(14) },
  // Kwara / Ilorin
  { id: "48", title: "2-Bedroom Flat in Ilorin", location: "GRA, Ilorin", city: "Ilorin", state: "Kwara", lga: "Ilorin West", price: 500000, priceLabel: "₦500,000/yr", beds: 2, baths: 1, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 70, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Well-finished 2-bedroom flat in the GRA area of Ilorin. Peaceful environment for families.", agent: agent(14) },
  // Osun / Osogbo
  { id: "49", title: "3-Bedroom Flat in Osogbo", location: "Oke-Baale, Osogbo", city: "Osogbo", state: "Osun", lga: "Osogbo", price: 450000, priceLabel: "₦450,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 85, parking: 1, amenities: ["Borehole", "Security", "Prepaid Meter"], description: "Affordable 3-bedroom flat in the heart of Osogbo. Close to the famous Osun-Osogbo Sacred Grove.", agent: agent(14) },
  // Ondo / Akure
  { id: "50", title: "3-Bedroom Bungalow in Akure", location: "Alagbaka, Akure", city: "Akure", state: "Ondo", lga: "Akure South", price: 800000, priceLabel: "₦800,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 100, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Well-finished 3-bedroom bungalow in the Alagbaka area. Close to the state secretariat.", agent: agent(14) },
  // Plateau / Jos
  { id: "51", title: "3-Bedroom Flat in Jos", location: "Rayfield, Jos", city: "Jos", state: "Plateau", lga: "Jos South", price: 700000, priceLabel: "₦700,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 95, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter"], description: "Comfortable 3-bedroom flat in the cool Rayfield area of Jos. Great weather year-round.", agent: agent(10) },
  // More Lagos
  { id: "52", title: "Luxury Shortlet in Lekki", location: "Lekki Phase 1, Lagos", city: "Lagos", state: "Lagos", lga: "Eti-Osa", price: 70000, priceLabel: "₦70,000/night", beds: 3, baths: 3, type: "Shortlet", image: img(4), verified: true, featured: true, furnished: true, sqm: 140, parking: 2, amenities: ["AC", "WiFi", "Swimming Pool", "Generator Backup", "Smart TV", "Gym", "Parking"], description: "Stunning luxury shortlet in Lekki Phase 1. Resort-style living with pool, gym, and panoramic views.", agent: agent(0) },
  { id: "53", title: "5-Bedroom Detached in Magodo", location: "Magodo Phase 2, Lagos", city: "Lagos", state: "Lagos", lga: "Kosofe", price: 95000000, priceLabel: "₦95,000,000", beds: 5, baths: 5, type: "Duplex", image: img(2), verified: true, featured: true, furnished: false, sqm: 400, parking: 4, amenities: ["Borehole", "24/7 Security", "Parking", "Generator Backup", "Swimming Pool", "Boys Quarter", "Garden", "CCTV"], description: "Magnificent 5-bedroom fully detached duplex in Magodo Phase 2. Premium estate with excellent infrastructure.", agent: agent(0) },
  { id: "54", title: "1-Bedroom Apartment in Ogba", location: "Ogba, Lagos", city: "Lagos", state: "Lagos", lga: "Ikeja", price: 800000, priceLabel: "₦800,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: true, featured: false, furnished: false, sqm: 35, parking: 0, amenities: ["Prepaid Meter", "Security", "POP Ceiling"], description: "Cozy 1-bedroom apartment in Ogba. Close to computer village and Ikeja CBD.", agent: agent(4) },
  { id: "55", title: "3-Bedroom Flat in Gbagada", location: "Gbagada Phase 2, Lagos", city: "Lagos", state: "Lagos", lga: "Kosofe", price: 2800000, priceLabel: "₦2,800,000/yr", beds: 3, baths: 2, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 110, parking: 1, amenities: ["Borehole", "Security", "Parking", "Prepaid Meter", "Generator Backup"], description: "Nicely finished 3-bedroom flat in Gbagada Phase 2 estate. Gated with excellent security.", agent: agent(8) },
  // More Abuja
  { id: "56", title: "Serviced 1-Bed in Kubwa", location: "Kubwa, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Bwari", price: 1200000, priceLabel: "₦1,200,000/yr", beds: 1, baths: 1, type: "Self Contain", image: img(5), verified: true, featured: false, furnished: false, sqm: 40, parking: 0, amenities: ["Borehole", "Security", "Prepaid Meter"], description: "Affordable serviced 1-bedroom in Kubwa. Good access to the city center via expressway.", agent: agent(10) },
  { id: "57", title: "3-Bedroom Terrace in Gwarinpa", location: "Gwarinpa, Abuja", city: "Abuja", state: "Abuja (FCT)", lga: "Municipal Area Council", price: 4500000, priceLabel: "₦4,500,000/yr", beds: 3, baths: 3, type: "Apartment", image: img(1), verified: true, featured: false, furnished: false, sqm: 150, parking: 2, amenities: ["Borehole", "Security", "Parking", "Generator Backup", "Prepaid Meter"], description: "Modern 3-bedroom terrace duplex in Gwarinpa estate. Well-maintained with serene environment.", agent: agent(1) },
  // Ekiti
  { id: "58", title: "2-Bedroom Flat in Ado-Ekiti", location: "Fajuyi, Ado-Ekiti", city: "Ado-Ekiti", state: "Ekiti", lga: "Ado-Ekiti", price: 350000, priceLabel: "₦350,000/yr", beds: 2, baths: 1, type: "Apartment", image: img(3), verified: true, featured: false, furnished: false, sqm: 60, parking: 0, amenities: ["Borehole", "Security", "Prepaid Meter"], description: "Clean 2-bedroom flat in Ado-Ekiti. Walking distance to the state secretariat and EKSU.", agent: agent(14) },
];
