import { createRouter, useRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/**
 * Default error boundary component for route-level errors
 *
 * TanStack Router automatically catches errors in route components
 * and renders this component. This is similar to Next.js error pages
 * but with more granular control per route.
 *
 * For React/Vite developers: This replaces traditional try-catch
 * error handling in route components.
 */
function DefaultErrorComponent({
  error,
  reset,
}: {
  error: Error;
  reset: () => void;
}) {
  const router = useRouter();

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-full bg-destructive/10">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-8 w-8 text-destructive"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"
            />
          </svg>
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-foreground">
          Something went wrong
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          An unexpected error occurred. Please try again.
        </p>
        {/* Show detailed error message only in development */}
        {import.meta.env.DEV && error.message && (
          <pre className="mt-4 max-h-40 overflow-auto rounded-md bg-muted p-3 text-left font-mono text-xs text-destructive">
            {error.message}
          </pre>
        )}
        <div className="mt-6 flex items-center justify-center gap-3">
          <button
            onClick={() => {
              // Invalidate all router data and reset error state
              // This is similar to window.location.reload() but more efficient
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
          >
            Go home
          </a>
        </div>
      </div>
    </div>
  );
}

/**
 * Router factory function
 *
 * Creates and configures the TanStack Router instance.
 * TanStack Router provides:
 * - Type-safe routing with full TypeScript support
 * - Route-based code splitting and preloading
 * - Search params and state management
 * - Nested routes and layouts
 * - Data loading and caching integration with TanStack Query
 *
 * For React/Vite developers: This replaces react-router-dom with
 * better TypeScript support and performance optimizations.
 */
export const getRouter = () => {
  const router = createRouter({
    // Auto-generated route tree from file-based routes in src/routes/
    // This file is generated by TanStack Start plugin during build
    routeTree,

    // How long preloaded route data is considered fresh (in milliseconds)
    // 0 means data is always considered stale and will be refetched on navigation
    // This ensures users always see the latest data
    defaultPreloadStaleTime: 0,

    // Global error boundary component for all routes
    // Individual routes can override this with their own errorComponent
    defaultErrorComponent: DefaultErrorComponent,
  });

  return router;
};
